import type { DocumentCategoryResponse, DocumentResponse } from "@/lib/api-types";

const NOW = new Date().toISOString();

const CATEGORIES: DocumentCategoryResponse[] = [
  {
    id: "company-overview",
    name: "Company Overview",
    slug: "company-overview",
    description: "High-level company overview materials",
    parent_category_id: null,
    sort_order: 1,
    is_active: true,
    created_at: NOW,
  },
  {
    id: "market-impact",
    name: "Market & Impact",
    slug: "market-impact",
    description: "Market sizing and impact metrics",
    parent_category_id: null,
    sort_order: 2,
    is_active: true,
    created_at: NOW,
  },
  {
    id: "financials",
    name: "Financials",
    slug: "financials",
    description: "Historicals and projections",
    parent_category_id: null,
    sort_order: 3,
    is_active: true,
    created_at: NOW,
  },
  {
    id: "ip-technology",
    name: "IP & Technology",
    slug: "ip-technology",
    description: "Product roadmap and technical docs",
    parent_category_id: null,
    sort_order: 4,
    is_active: true,
    created_at: NOW,
  },
  {
    id: "traction",
    name: "Traction",
    slug: "traction",
    description: "Customer traction and growth data",
    parent_category_id: null,
    sort_order: 5,
    is_active: true,
    created_at: NOW,
  },
  {
    id: "legal",
    name: "Legal",
    slug: "legal",
    description: "Key legal and governance documents",
    parent_category_id: null,
    sort_order: 6,
    is_active: true,
    created_at: NOW,
  },
];

const DOCUMENTS: DocumentResponse[] = [
  {
    id: "pitch-deck-2025",
    category_id: "company-overview",
    title: "SAYeTECH Pitch Deck 2025",
    description: "Primary fundraising presentation",
    file_name: "SAYeTECH Pitch Deck 2025.pdf",
    file_type: "application/pdf",
    file_size: 4_200_000,
    version_number: 3,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "executive-summary",
    category_id: "company-overview",
    title: "Executive Summary",
    description: "One-page summary of SAYeTECH",
    file_name: "Executive Summary.pdf",
    file_type: "application/pdf",
    file_size: 1_100_000,
    version_number: 2,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "team-bios",
    category_id: "company-overview",
    title: "Team Bios",
    description: "Leadership bios and background",
    file_name: "Team Bios.pdf",
    file_type: "application/pdf",
    file_size: 850_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "market-analysis",
    category_id: "market-impact",
    title: "Market Analysis Report",
    description: "Market sizing and competitive landscape",
    file_name: "Market Analysis Report.pdf",
    file_type: "application/pdf",
    file_size: 3_500_000,
    version_number: 2,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "impact-metrics",
    category_id: "market-impact",
    title: "Impact Metrics Overview",
    description: "Key impact metrics overview",
    file_name: "Impact Metrics Overview.pdf",
    file_type: "application/pdf",
    file_size: 2_100_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "financial-model",
    category_id: "financials",
    title: "Financial Model 2025-2028",
    description: "Forward-looking financial model",
    file_name: "Financial Model 2025-2028.pdf",
    file_type: "application/pdf",
    file_size: 5_800_000,
    version_number: 4,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "historical-financials",
    category_id: "financials",
    title: "Historical Financials",
    description: "Historical P&L and balance sheet",
    file_name: "Historical Financials.pdf",
    file_type: "application/pdf",
    file_size: 1_900_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "product-roadmap",
    category_id: "ip-technology",
    title: "Product Roadmap",
    description: "High-level product roadmap",
    file_name: "Product Roadmap.pdf",
    file_type: "application/pdf",
    file_size: 2_300_000,
    version_number: 2,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "technical-architecture",
    category_id: "ip-technology",
    title: "Technical Architecture",
    description: "System architecture overview",
    file_name: "Technical Architecture.pdf",
    file_type: "application/pdf",
    file_size: 3_100_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "growth-metrics",
    category_id: "traction",
    title: "Growth Metrics Q4 2024",
    description: "Latest growth and engagement metrics",
    file_name: "Growth Metrics Q4 2024.pdf",
    file_type: "application/pdf",
    file_size: 1_700_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "customer-case-studies",
    category_id: "traction",
    title: "Customer Case Studies",
    description: "Selected customer stories",
    file_name: "Customer Case Studies.pdf",
    file_type: "application/pdf",
    file_size: 4_500_000,
    version_number: 2,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "cap-table",
    category_id: "legal",
    title: "Cap Table",
    description: "Current capitalization table",
    file_name: "Cap Table.pdf",
    file_type: "application/pdf",
    file_size: 890_000,
    version_number: 5,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "articles-of-incorporation",
    category_id: "legal",
    title: "Articles of Incorporation",
    description: "Incorporation documents",
    file_name: "Articles of Incorporation.pdf",
    file_type: "application/pdf",
    file_size: 1_500_000,
    version_number: 1,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
  {
    id: "material-contracts",
    category_id: "legal",
    title: "Material Contracts",
    description: "Key customer and partner contracts",
    file_name: "Material Contracts.pdf",
    file_type: "application/pdf",
    file_size: 6_200_000,
    version_number: 2,
    is_latest_version: true,
    uploaded_by: "SAYeTECH Team",
    uploaded_at: NOW,
    updated_at: NOW,
  },
];

export function getCategories(parentId?: string | null): DocumentCategoryResponse[] {
  if (parentId) {
    return CATEGORIES.filter((cat) => cat.parent_category_id === parentId);
  }
  return CATEGORIES.filter((cat) => cat.parent_category_id === null);
}

export function getDocumentsByCategoryId(categoryId: string): DocumentResponse[] {
  return DOCUMENTS.filter((doc) => doc.category_id === categoryId);
}

export function getDocumentById(documentId: string): DocumentResponse | undefined {
  return DOCUMENTS.find((doc) => doc.id === documentId);
}
